### ISSUE TITLE
Username makes multi login

### ISSUE THREAD

**Issue by josephmiller2000** [KMKNKK/Chatroom-WebScoket#1]
When i set username >> ok ok 

Chat system decides that two person is log in and makes it as dual login.

![snap_2018 05 04_23h13m54s_002_](https://user-images.githubusercontent.com/24210340/39642986-f1afa548-4ff0-11e8-9684-a4a05ba5d924.png)

**Comment by KMKNKK** [comment]
Sorry, I only noticed this issue now.
I checked and found that it was caused by the repeated connection of Websocket. Now I have fixed this bug, thank you for your feedback!
